[images]
  remote_images = ["https://mediacontent3.rebuydeal.com/products/.*", "https://fdn2.gsmarena.com/vv/pics/samsung/.*", "https://cdn1.ecomtreasure.com/wp-content/uploads/2022/10/.*", "https://daisyui.com/images/stock/.*"]
